config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#front'
  resources :products  do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :text, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '風景' },
    { id: 3, name: '動物' },
    { id: 4, name: '地域' },
    { id: 5, name: '国' },
    { id: 6, name: '日常' },
    { id: 7, name: 'ユーモア' },
    { id: 8, name: 'スポーツ' },
    { id: 9, name: 'グルメ' },
    { id: 10, name: 'ファッション' },
    { id: 11, name: 'その他' }
  ]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes
  acts_as_taggable
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  with_options presence: true do
    validates :text, :images
    validates :genre_id, numericality: { other_than: 1 }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes

  def liked_by?(product_id)
    likes.where(product_id: product_id).exists?
  end

  with_options presence: true do
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    number = /\A[a-zA-Z0-9]+\z/
    validates :nickname
    validates :email, { uniqueness: true, format: { with: VALID_EMAIL_REGEX } }
    validates :password, { length: { minimum: 6 }, confirmation: true, format: { with: number } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    products_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/products/#{comment.product.id}"
  end

  def destroy
    Comment.find_by(id: params[:id], product_id: params[:product_id]).destroy
    redirect_to products_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, product_id: params[:product_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!

  def front
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :product_set

  def create
    Like.create(user_id: current_user.id, product_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, product_id: params[:id]).destroy
  end

  private

  def product_set
    @product = Product.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :product_set, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.includes(:user).order('created_at DESC')
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.valid?
      @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_path
    else
      render :show
    end
  end

  private

  def product_params
    params.require(:product).permit(:text, :genre_id, :tag_list, { images: [] }).merge(user_id: current_user.id)
  end

  def product_set
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @nickname = current_user.nickname
    @products = current_user.products
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to  products_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/front.html.erb
<div class='top-box' id="top">
  <header class='top-page-header'>
      <%= link_to 'Post', products_path, class:"product-icon" %>
    <div class='nav'>
      <ul class='lists-left'>
        <li><%= link_to 'New Post', new_product_path, class: "new-list"%></li>
      </ul>
      <ul class='lists-right'>
        <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "#", class: "user-nickname"%></li>
        <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "logout"%></li> 
        <% else %>
        <li><%= link_to 'login', new_user_session_path, class: "login"%></li>
        <li><%= link_to 'sign-up', new_user_registration_path, class: "sign-up"%></li>
        <% end %>
      </ul>
    </div>
  </header>
  
  <div class='top-middle'>
    <p class='top-title', id="index-image">P h o t o   P  O  S  T</p>
    <br>
    <h2 class='top-sabu'>One of your favorites..</h2>
    <div class='image-top'>
      <div class='image-one'>
          <%= image_tag "download.jpg", class:"nature-icon"%>
      </div>
      <div class='image-one'>
          <%= image_tag "dog.jpg", class: "nature-icon"%>
      </div>
      <div class='image-one'>
          <%= image_tag "download1.jpg", class: "nature-icon"%>
      </div>
      <div class='image-one'>
          <%= image_tag "island.jpg", class: "nature-icon"%>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
document.getElementById('product_<%= @product.id %>').innerHTML = '<%= j(render @product) %>'

app/views/likes/destroy.js.erb
document.getElementById('product_<%= @product.id %>').innerHTML = '<%= j(render @product) %>'

app/views/products/_comment.html.erb
<div class="message">
  <%# <strong><%= link_to @product.user.nickname：</strong> %>
  <p><%= comment.text %></p>
</div>

app/views/products/_product.html.erb
<% if current_user.liked_by?(@product.id) %>
  <td>
    <%= link_to destroy_like_path(@product.id), class: "like-link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart unlike-btn">いいね外す</i>
    <% end %>
    <%= @product.likes.count %>
  </td>
<% else %>
  <td>
    <%= link_to create_like_path(@product.id), class: "like-link", method: :POST, remote: true do %>
      <i class="fa fa-heart like-btn">いいね</i>
    <% end %>
    <%= @product.likes.count %>
  </td>
<% end %>

app/views/products/_tag_list.html.erb
<% tag_list.each do |tag| %>
<span class='item-tag'>
  <%= tag %>
</span>
<% end %>

app/views/products/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/products/new.css %>

<div class="products-sell-contents">
  <header class="products-sell-header">
     <%= link_to 'POST', products_path, class:"second-logo"%>
  </header>
  <div class="products-sell-main">
    <h2 class="products-sell-title">POST</h2>
    <%= form_with(model: @product, local: true) do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%#= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        image
      </div>
      <div class="click-upload">
        <p>
          画像選択
        </p>
         <%= f.file_field :images, name: 'product[images][]', id:'items_image' %>
         <div id = "item-image"></div>
         <% @product.images.each do |image| %>
           <%= image_tag image, class: 'images' %>
         <% end %>
      </div>
    </div>
    <%# /画像 %>
    <%# 内容 %>
      <div class="new-products">
        <div class="products-explain">
          <%= f.label :text %>
          <%= f.text_area :text, class:"products-text", id:"item-info", placeholder:"type a message", rows:"7" ,maxlength:"1000" %>
        </div>
      <div class="products-detail">
        <div class="weight-bold-text">Genre</div>
        <div class="form">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
        <div class="products-detail"> 
          <div class="weight-bold-text">
          <%= f.label :tag_list %>
          </div>
          <%= f.text_field :tag_list, value: @product.tag_list.join(','), class: "form-control", placeholder:"海,やま,sky"%>
        </div>
      </div>
      <%# /内容 %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "POST" ,class:"sell-btn" %>
        <%=link_to 'RETURN', product_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/products/index.html.erb
<%= render "shared/header" %>
<div class='title-contents'>
    <p class='photo-title'>Photo List</p>
</div>
<div class='box'>
  <div class='photo-list'>
    <div>
      <ul class='item-lists'>
        <% @products.each do |product| %>
            <li class='list'>
              <%= link_to product_path(product.id), method: :get do %>
              <div class='item-img-content'>
                <%= image_tag product.images[0], class:"item-img" %>
              </div>
             <% end %>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= product.text %>
                </h3>
               </div>
               <div class="tag-top">
                <%= render 'products/tag_list', tag_list: product.tag_list%>
               </div>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/products/new.html.erb
<div class="products-sell-contents">
  <header class="products-sell-header">
    <%= link_to 'POST', products_path, class:"second-logo"%>
  </header>
  <div class="products-sell-main">
      <h2 class="products-sell-title">POST</h2>
      <%= form_with(model: @product, local: true) do |f| %>

      <%# 画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          image
        </div>
        <div class="click-upload">
          <p>
            画像選択
          </p>
          <%= f.file_field :images, name: 'product[images][]', id:'items_image' %>
          <div id = "item-image"></div>
          <% @product.images.each do |image| %>
            <%= image_tag image, class: 'images' %>
          <% end %>
        </div>
      </div>
      <%# /画像 %>
      <%# 内容 %>
      <div class="new-products">
        <div class="products-explain">
          <%= f.label :text %>
          <%= f.text_area :text, class:"products-text", id:"item-info", placeholder:"type a message", rows:"7" ,maxlength:"1000" %>
        </div>
      <div class="products-detail">
        <div class="weight-bold-text">Genre</div>
        <div class="form">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
        <div class="products-detail"> 
          <div class="weight-bold-text">
          <%= f.label :tag_list %>
          </div>
          <%= f.text_field :tag_list, value: @product.tag_list.join(','), class: "form-control", placeholder:"海,やま,sky"%>
        </div>
      </div>
      <%# /内容 %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "POST" ,class:"sell-btn" %>
        <%=link_to 'RETURN', products_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/products/show.html.erb
<%= render "shared/header" %>

<%# 投稿の概要 %>
<div class="item-show">
  <%# 投稿者のみ削除可能%>
    <div class="item-show-two">
    <% if user_signed_in? && @product.user.id == current_user.id %>
    <%= link_to '編集', edit_product_path(@product.id), method: :get, class: "item-red-btn" %>
    <%= link_to '削除', product_path(@product.id), method: :delete, class:'item-destroy' %>
    <% end %>
    </div>
    <%# // 投稿者のみ削除可能 %>

  <div class="item-box">
    <div class="previews">
      <div class="slider">
        <% @product.images.each do |image|%>
          <%= image_tag image, class:"item-box-img" %>
        <% end %>
      </div>
    </div>
    <div class="like-button">
      <table>
      <tbody>
      <tr  id="product_<%= @product.id %>">
         <%= render 'product', product: @product %>
      </tr>
      </tbody>
      </table>
    </div>
    <div class="item-explain-box">
      <span><%= @product.text %></span>
    </div>
    <div class="genre-show">
       <span class="tag_tag_list">Genre : </span>
       <%= @product.genre.name %>
    </div>
    <div class="tag-top-show">
       <span class="tag_tag_list">Tag list : </span>
      <%= render 'products/tag_list', tag_list: @product.tag_list%>
    </div>
  </div>
  <%# /投稿の概要 %>
      
  <div class="comment-box">
       <% if current_user %>
        <%= form_with(model: [@product, @comment], local: true) do |form| %>
          <%= form.text_area :text, placeholder: "コメントする", class:"comment-text" %>
            <button type="submit" class="comment-btn">
              <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
            <span>コメントする<span>
            </button>
        <% end %>
       <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
       <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% if @comments %>
        <% @comments.each do |comment| %>
            <p>
              <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong> 
            <%= comment.text %> 
            </p>
          <p><%=link_to "削除", product_comment_path(comment.product.id, comment.id), method: :delete %></p> 
        <% end %> 
      <% end %> 
    </div> 
  </div> 
</div>  

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <p>© POST</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
    <%= link_to 'Post', products_path, class:"product-icon" %>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'New Post', new_product_path, class: "new-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, edit_user_path(current_user), class: "user-nickname" %></li>
      <li><%= link_to 'Mypage', "/users/#{current_user.id}", class: "mypage" %></li>
      <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
      <li><%= link_to 'login', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'sign-up', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to 'POST', root_path, class:"second-logo"%>
</header>

app/views/users/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: current_user, class: 'edit-main', local: true do |f|%>
<div class='edit-wrap'>
   <div class='edit-header'>
      <h2 class="edit-account">Edit Account</h2>
    </div>
 
    <div class="edit-form-group">
      <div class='edit-form-text-wrap'>
        <label class="edit-form-text">ニックネーム</label>
      </div>
      <%= f.text_area :nickname, class:"edit-input-default", id:"nickname", placeholder:"例) Minto", maxlength:"40" %>
    </div>
    <div class="edit-form-group">
      <div class='edit-form-text-wrap'>
        <label class="edit-form-text">メールアドレス</label>
      </div>
      <%= f.email_field :email, class:"edit-input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
    </div>
    <div class='edit-register-btn'>
      <%= f.submit "Update" ,class:"edit-register-update-btn" %>
    </div>
</div>
<% end %>

<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class='photo-list'>
    <div class="nickname-font">
      <p class="nickname"><%= @nickname %>さんの投稿一覧</p>
    </div>
    <div>
      <ul class='item-lists'>
        <% @products.each do |product| %>
            <li class='list'>
              <%= link_to product_path(product.id), method: :get do %>
              <div class='item-img-content'>
                <%= image_tag product.images[0], class:"item-img" %>
              </div>
            <% end %>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= product.text %>
                </h3>
              </div>
              <div class="tag-top">
                <%= render 'products/tag_list', tag_list: product.tag_list%>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
</div>


<%= render "shared/footer" %>